language: java
jdk:
    - openjdk8
sudo: false # faster builds

script:
        - "mvn clean verify jacoco:report jacoco:report-integration -Pquality -Pparallel"
after_success:
        - "mvn coveralls:report -Pquality"
